name: Post message to WxT

on: push

jobs:
  wxt:
    runs-on: ubuntu-latest
    steps:
      - name: Post message to WxT
        uses: qsnyder/action-wxt
        env:
          TOKEN: ${{ secrets.TOKEN }}
          ROOMID: ${{ secrets.ROOMID }}
          MESSAGE: Testing post to WxT
