name: Post message to WxT

on: push

jobs:
  wxt:
    runs-on: ubuntu-latest
    steps:
      - name: Post message to WxT
        uses: qsnyder/action-wxt@master
        env:
          TOKEN: ${{ secrets.TOKEN }}
          ROOMID: ${{ secrets.ROOMID }}
          MESSAGE: "Run ${{ github.run_number }} completed successfully, triggered by user ${{ github.actor }} with commit SHA ${{ github.sha }}"
